{application,mint_web_socket,
             [{modules,['Elixir.Mint.WebSocket',
                        'Elixir.Mint.WebSocket.Extension',
                        'Elixir.Mint.WebSocket.Frame',
                        'Elixir.Mint.WebSocket.PerMessageDeflate',
                        'Elixir.Mint.WebSocket.UpgradeFailureError',
                        'Elixir.Mint.WebSocket.Utils',
                        'Elixir.Mint.WebSocketError']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,mint]},
              {description,"HTTP/1 and HTTP/2 WebSocket support for Mint"},
              {registered,[]},
              {vsn,"1.0.5"}]}.
